// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqhpciikypyiophscfzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xaHBjaWlreXB5aW9waHNjZnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzYyNzUsImV4cCI6MjA2OTExMjI3NX0.DrELJDKAwMDjlZM2rx29xVFAXPzylWL62kd6Vl2A8cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});